"""
venues/seeds_venues.py — Curated seed venues for SNITC rooftop venue search.

Pre-researched rooftop/outdoor venues in Brooklyn & Manhattan, NYC.
The scraper pipeline will fetch live pages to enrich with contact info,
capacity data, and current booking availability signals.

Sorted: Brooklyn (priority) first → Manhattan second
"""

SEED_VENUES = [

    # ═══════════════════════════════════════════════
    # BROOKLYN — Williamsburg
    # ═══════════════════════════════════════════════
    {
        "venue_name":   "The Ides at Wythe Hotel",
        "location":     "80 Wythe Ave, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Hotel Rooftop Bar",
        "description":  "Iconic rooftop bar atop Wythe Hotel with sweeping Manhattan skyline views. Known for private events and a vibrant nightlife scene.",
        "website":      "https://wythehotel.com/eat-drink/the-ides/",
        "contact":      "events@wythehotel.com",
        "notes":        "Known for nightlife events, indoor backup available, full bar. Private buyout available.",
        "source_url":   "https://wythehotel.com",
    },
    {
        "venue_name":   "Westlight",
        "location":     "111 N 12th St, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Hotel Rooftop Bar",
        "description":  "22nd-floor rooftop bar at The William Vale hotel with panoramic NYC views, cocktail bar, and private event space.",
        "website":      "https://www.williamvale.com/westlight",
        "contact":      "events@williamvale.com",
        "notes":        "Panoramic views, elevated cocktail program, private event buyout available. One of Brooklyn's top rooftop bars.",
        "source_url":   "https://www.williamvale.com",
    },
    {
        "venue_name":   "Berry Park",
        "location":     "4 Berry St, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Rooftop Bar",
        "description":  "Multi-level rooftop beer garden in Williamsburg with large outdoor terrace. One of Brooklyn's most spacious rooftop bars.",
        "website":      "https://www.berryparkbk.com",
        "contact":      "",
        "notes":        "Large rooftop terrace, known for nightlife events, DJ-friendly. Check private event availability.",
        "source_url":   "https://www.berryparkbk.com",
    },
    {
        "venue_name":   "Kinfolk 94",
        "location":     "94 Wythe Ave, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Event Space / Rooftop",
        "description":  "Brooklyn creative event space with rooftop access, DJ booth, and full bar. Frequently hosts cultural and music events.",
        "website":      "https://www.kinfolk94.com",
        "contact":      "events@kinfolk94.com",
        "notes":        "Hosts Afrobeats/cultural events. Has DJ booth & sound system. Indoor + rooftop. Strong nightlife programming.",
        "source_url":   "https://www.kinfolk94.com",
    },
    {
        "venue_name":   "Brooklyn Winery",
        "location":     "213 N 8th St, Brooklyn, NY 11211",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Event Space",
        "description":  "Williamsburg urban winery with stylish event spaces including a rooftop terrace, full bar, and kitchen.",
        "website":      "https://bkwinery.com/private-events/",
        "contact":      "events@bkwinery.com",
        "notes":        "Flexible event spaces, rooftop terrace, in-house catering, full bar. Private buyout available.",
        "source_url":   "https://bkwinery.com",
    },

    # ═══════════════════════════════════════════════
    # BROOKLYN — Bushwick / East Williamsburg
    # ═══════════════════════════════════════════════
    {
        "venue_name":   "Elsewhere",
        "location":     "599 Johnson Ave, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Music Venue / Rooftop",
        "description":  "Multi-room Brooklyn nightlife venue with an outdoor rooftop stage, indoor halls, and full bar. Known for diverse music programming.",
        "website":      "https://www.elsewherebrooklyn.com",
        "contact":      "hello@elsewherebrooklyn.com",
        "notes":        "Has hosted Afrobeats/Amapiano events. Rooftop stage + indoor backup. Sound system. Priority lead for SNITC.",
        "source_url":   "https://www.elsewherebrooklyn.com",
    },
    {
        "venue_name":   "Nowadays",
        "location":     "56 Wyckoff Ave, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Outdoor Club / Garden",
        "description":  "Year-round outdoor dance venue with garden, sound stage, and full bar. NYC's premier outdoor dance music spot.",
        "website":      "https://nowadays.nyc",
        "contact":      "info@nowadays.nyc",
        "notes":        "Outdoor garden + indoor option. Strong DJ/dance culture. Has hosted African/diaspora events. Sound system included.",
        "source_url":   "https://nowadays.nyc",
    },
    {
        "venue_name":   "House of Yes",
        "location":     "2 Wyckoff Ave, Brooklyn, NY 11237",
        "neighborhood": "Bushwick",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Event Venue / Outdoor Space",
        "description":  "Iconic Bushwick event and performance space with outdoor patio, circus rigging, and vibrant arts programming.",
        "website":      "https://houseofyes.org",
        "contact":      "events@houseofyes.org",
        "notes":        "Strong nightlife/cultural programming. Outdoor space + indoor. DJ booth, sound system. Good SNITC fit.",
        "source_url":   "https://houseofyes.org",
    },

    # ═══════════════════════════════════════════════
    # BROOKLYN — Greenpoint
    # ═══════════════════════════════════════════════
    {
        "venue_name":   "Le Bain at The Standard Brooklyn",
        "location":     "25 Little W 12th St, Brooklyn, NY (check Greenpoint location)",
        "neighborhood": "Greenpoint",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Hotel Rooftop Bar",
        "description":  "Rooftop club and bar with Manhattan skyline views, dance floor, and pool. Premium event space known for nightlife.",
        "website":      "https://www.standardhotels.com/lebain",
        "contact":      "events@standardhotels.com",
        "notes":        "Indoor/outdoor rooftop, dance floor, DJ booth. Strong nightlife programming. Buyout available.",
        "source_url":   "https://www.standardhotels.com",
    },
    {
        "venue_name":   "The Greenpoint Hotel Rooftop",
        "location":     "160 Calyer St, Brooklyn, NY 11222",
        "neighborhood": "Greenpoint",
        "borough":      "Brooklyn",
        "capacity":     "200",
        "venue_type":   "Hotel Rooftop",
        "description":  "Rooftop event space at The Greenpoint Hotel with Manhattan skyline views and private event capabilities.",
        "website":      "https://thegreenpointhotel.com",
        "contact":      "events@thegreenpointhotel.com",
        "notes":        "Skyline views, private event buyout, full bar service. Boutique hotel rooftop.",
        "source_url":   "https://thegreenpointhotel.com",
    },
    {
        "venue_name":   "Dobbin St",
        "location":     "13 Dobbin St, Brooklyn, NY 11222",
        "neighborhood": "Greenpoint",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Event Space / Rooftop Terrace",
        "description":  "Converted warehouse event space in Greenpoint with rooftop deck, industrial aesthetic, and flexible layout.",
        "website":      "https://dobbinst.com",
        "contact":      "info@dobbinst.com",
        "notes":        "Rooftop deck + indoor space. Flexible layout. Hosts cultural events and private parties. Good for nightlife.",
        "source_url":   "https://dobbinst.com",
    },

    # ═══════════════════════════════════════════════
    # BROOKLYN — DUMBO
    # ═══════════════════════════════════════════════
    {
        "venue_name":   "1 Hotel Brooklyn Bridge Rooftop",
        "location":     "60 Furman St, Brooklyn, NY 11201",
        "neighborhood": "DUMBO",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Hotel Rooftop",
        "description":  "Luxury eco-hotel rooftop with stunning views of Brooklyn Bridge and Manhattan skyline. Premium private event space.",
        "website":      "https://www.1hotels.com/brooklyn-bridge/spaces/rooftop",
        "contact":      "events.brooklyn@1hotels.com",
        "notes":        "Bridge + skyline views, luxury finishes, full bar, indoor backup. Min spend likely $10K+. Premium lead.",
        "source_url":   "https://www.1hotels.com/brooklyn-bridge",
    },
    {
        "venue_name":   "The Dumbo Loft",
        "location":     "155 Water St, Brooklyn, NY 11201",
        "neighborhood": "DUMBO",
        "borough":      "Brooklyn",
        "capacity":     "200",
        "venue_type":   "Event Loft / Terrace",
        "description":  "Industrial loft event space in DUMBO with outdoor terrace and dramatic views of Manhattan Bridge.",
        "website":      "https://www.thedumboloft.com",
        "contact":      "info@dumboloft.com",
        "notes":        "Manhattan Bridge views, outdoor terrace, flexible layout. Good for 200-cap events.",
        "source_url":   "https://www.thedumboloft.com",
    },
    {
        "venue_name":   "Celestine",
        "location":     "1 John St, Brooklyn, NY 11201",
        "neighborhood": "DUMBO",
        "borough":      "Brooklyn",
        "capacity":     "200",
        "venue_type":   "Restaurant Terrace",
        "description":  "Mediterranean restaurant in DUMBO with a stunning outdoor terrace overlooking Brooklyn Bridge Park and Manhattan skyline.",
        "website":      "https://celestinebk.com/private-events/",
        "contact":      "events@celestinebk.com",
        "notes":        "Waterfront, Brooklyn Bridge Park views. Rooftop/terrace dining. Private event buyout available with in-house catering.",
        "source_url":   "https://celestinebk.com",
    },

    # ═══════════════════════════════════════════════
    # BROOKLYN — Brooklyn Heights / Cobble Hill / BK General
    # ═══════════════════════════════════════════════
    {
        "venue_name":   "501 Union",
        "location":     "501 Union St, Brooklyn, NY 11215",
        "neighborhood": "Gowanus",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Event Space / Garden",
        "description":  "Eclectic Brooklyn event space with multiple rooms, outdoor garden, and sophisticated aesthetic for private events.",
        "website":      "https://501union.com",
        "contact":      "info@501union.com",
        "notes":        "Outdoor garden + indoor spaces, full bar, flexible layout. Private events only. Good SNITC fit.",
        "source_url":   "https://501union.com",
    },
    {
        "venue_name":   "Brooklyn Grange Rooftop Farm",
        "location":     "63 Flushing Ave, Brooklyn, NY 11205",
        "neighborhood": "Navy Yard",
        "borough":      "Brooklyn",
        "capacity":     "200",
        "venue_type":   "Rooftop Farm / Event Space",
        "description":  "Working rooftop farm with event space offering unique Brooklyn skyline views and sustainable event programming.",
        "website":      "https://brooklyngrange.com/venue-rentals/",
        "contact":      "events@brooklyngrange.com",
        "notes":        "Unique rooftop farm setting, skyline views, outdoor space. Capacity ~200 standing. Distinctive venue.",
        "source_url":   "https://brooklyngrange.com",
    },
    {
        "venue_name":   "The Reef",
        "location":     "179 Atlantic Ave, Brooklyn, NY 11201",
        "neighborhood": "Brooklyn Heights",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Event Space / Rooftop Bar",
        "description":  "Rooftop bar and event space in Brooklyn Heights with waterfront proximity and strong nightlife programming.",
        "website":      "https://thereefnyc.com",
        "contact":      "events@thereefnyc.com",
        "notes":        "Rooftop bar, nightlife programming, waterfront area. Check private event capacity.",
        "source_url":   "https://thereefnyc.com",
    },
    {
        "venue_name":   "Pig Beach",
        "location":     "480 Union St, Brooklyn, NY 11231",
        "neighborhood": "Gowanus",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Outdoor Bar / Event Space",
        "description":  "Large outdoor bar and BBQ joint in Gowanus with expansive beer garden. Known for large private events.",
        "website":      "https://www.pigbeachnyc.com",
        "contact":      "events@pigbeachnyc.com",
        "notes":        "Large outdoor space, 300 cap, full bar and food. Private event buyout available. Good summer venue.",
        "source_url":   "https://www.pigbeachnyc.com",
    },

    # ═══════════════════════════════════════════════
    # BROOKLYN — Bed-Stuy / Crown Heights / Other
    # ═══════════════════════════════════════════════
    {
        "venue_name":   "Maison Premiere",
        "location":     "298 Bedford Ave, Brooklyn, NY 11211",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "200",
        "venue_type":   "Oyster Bar / Garden",
        "description":  "New Orleans-inspired oyster bar with an enchanting rear garden perfect for private events and summer parties.",
        "website":      "https://maisonpremiere.com/private-events/",
        "contact":      "events@maisonpremiere.com",
        "notes":        "Garden terrace, private events, craft cocktail bar. Intimate and elevated. Check outdoor capacity.",
        "source_url":   "https://maisonpremiere.com",
    },
    {
        "venue_name":   "The NuBlu Brooklyn",
        "location":     "62 Whipple St, Brooklyn, NY 11206",
        "neighborhood": "Bushwick",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Music Venue / Outdoor",
        "description":  "Brooklyn music and event venue with outdoor terrace and bar. Known for diverse music events including Afrobeats nights.",
        "website":      "https://nublu.net",
        "contact":      "info@nublu.net",
        "notes":        "Has hosted Caribbean/African music events. Outdoor space, sound system, bar service.",
        "source_url":   "https://nublu.net",
    },
    {
        "venue_name":   "Syndicated BK",
        "location":     "40 Bogart St, Brooklyn, NY 11206",
        "neighborhood": "Bushwick",
        "borough":      "Brooklyn",
        "capacity":     "200",
        "venue_type":   "Bar / Event Space",
        "description":  "Bushwick bar and cinema with large back patio event space. Regularly hosts private events and themed nights.",
        "website":      "https://syndicatedbk.com",
        "contact":      "info@syndicatedbk.com",
        "notes":        "Outdoor patio, private events, full bar. DJ-friendly. Capacity ~200.",
        "source_url":   "https://syndicatedbk.com",
    },

    # ═══════════════════════════════════════════════
    # MANHATTAN — Lower East Side / East Village
    # ═══════════════════════════════════════════════
    {
        "venue_name":   "Kiki on the River",
        "location":     "130 Barrow St (see current address), New York, NY",
        "neighborhood": "Lower East Side",
        "borough":      "Manhattan",
        "capacity":     "300",
        "venue_type":   "Waterfront Terrace / Club",
        "description":  "Stylish waterfront event venue with large outdoor terrace and panoramic Hudson River views, known for nightlife events.",
        "website":      "https://kikiontheriver.com",
        "contact":      "events@kikiontheriver.com",
        "notes":        "Waterfront views, large outdoor space, nightlife programming. Check private event buyout terms.",
        "source_url":   "https://kikiontheriver.com",
    },
    {
        "venue_name":   "Mr. Purple at Hotel Indigo LES",
        "location":     "180 Orchard St, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough":      "Manhattan",
        "capacity":     "250",
        "venue_type":   "Hotel Rooftop Bar",
        "description":  "15th-floor rooftop pool bar on the LES with sweeping city views, outdoor terrace, and private event capabilities.",
        "website":      "https://mrpurplenyc.com",
        "contact":      "events@mrpurplenyc.com",
        "notes":        "Rooftop pool, city views, private event buyout. LES nightlife scene. Good cultural event fit.",
        "source_url":   "https://mrpurplenyc.com",
    },
    {
        "venue_name":   "PHD Terrace at Dream Midtown",
        "location":     "355 W 16th St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough":      "Manhattan",
        "capacity":     "300",
        "venue_type":   "Hotel Rooftop Bar",
        "description":  "Chic rooftop bar and terrace topping Dream Midtown hotel with skyline views, full bar, and VIP event capabilities.",
        "website":      "https://www.dreamhotels.com/midtown/phd-terrace",
        "contact":      "events@dreamhotels.com",
        "notes":        "Skyline views, nightlife programming, private event space. Known as NYC hotspot.",
        "source_url":   "https://www.dreamhotels.com/midtown",
    },
    {
        "venue_name":   "Le Bain at The Standard, High Line",
        "location":     "848 Washington St, New York, NY 10014",
        "neighborhood": "Meatpacking District",
        "borough":      "Manhattan",
        "capacity":     "300",
        "venue_type":   "Hotel Rooftop Club",
        "description":  "Iconic rooftop club and disco bar at The Standard Hotel, High Line, with Hudson River views and a plunge pool.",
        "website":      "https://www.standardhotels.com/new-york/properties/high-line/lebain",
        "contact":      "lebain@standardhotels.com",
        "notes":        "Iconic NYC nightlife rooftop. DJ booth, dance floor, pool. Private events available. Premium venue.",
        "source_url":   "https://www.standardhotels.com",
    },
    {
        "venue_name":   "1 OAK NYC",
        "location":     "453 W 17th St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough":      "Manhattan",
        "capacity":     "300",
        "venue_type":   "Nightclub / Event Space",
        "description":  "Legendary Manhattan nightclub with VIP areas, large main room, and private event capabilities for 200-300 guests.",
        "website":      "https://www.1oaknyc.com",
        "contact":      "info@1oaknyc.com",
        "notes":        "High-end nightlife venue, private parties, DJ booth. Strong nightlife pedigree for SNITC event type.",
        "source_url":   "https://www.1oaknyc.com",
    },
    {
        "venue_name":   "Cantina Rooftop",
        "location":     "155 W 18th St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough":      "Manhattan",
        "capacity":     "250",
        "venue_type":   "Restaurant Rooftop",
        "description":  "Mexican rooftop restaurant in Chelsea with large outdoor terrace, tequila bar, and private event space.",
        "website":      "https://cantinanyc.com/private-events/",
        "contact":      "events@cantinanyc.com",
        "notes":        "Large rooftop terrace, full bar, in-house catering. Private events available.",
        "source_url":   "https://cantinanyc.com",
    },
    {
        "venue_name":   "230 Fifth Rooftop Bar",
        "location":     "230 Fifth Ave, New York, NY 10001",
        "neighborhood": "Flatiron",
        "borough":      "Manhattan",
        "capacity":     "300",
        "venue_type":   "Rooftop Bar",
        "description":  "NYC's largest outdoor rooftop bar with unobstructed Empire State Building views and large event space suitable for 200-300.",
        "website":      "https://www.230-fifth.com/private-events/",
        "contact":      "events@230-fifth.com",
        "notes":        "Empire State Building view, huge rooftop, private event buyout available. Well-known event venue.",
        "source_url":   "https://www.230-fifth.com",
    },
    {
        "venue_name":   "Skylark NYC",
        "location":     "200 W 39th St, New York, NY 10018",
        "neighborhood": "Midtown",
        "borough":      "Manhattan",
        "capacity":     "250",
        "venue_type":   "Rooftop Bar",
        "description":  "Upscale rooftop bar on the 30th floor with panoramic Manhattan views and sophisticated private event capabilities.",
        "website":      "https://theskylarknyc.com/private-events/",
        "contact":      "events@theskylarknyc.com",
        "notes":        "Panoramic 30th-floor views, full bar, private event space. Elegant setting.",
        "source_url":   "https://theskylarknyc.com",
    },
    {
        "venue_name":   "Westway NYC",
        "location":     "40 W 30th St, New York, NY 10001",
        "neighborhood": "Midtown South",
        "borough":      "Manhattan",
        "capacity":     "300",
        "venue_type":   "Nightclub / Event Space",
        "description":  "Midtown nightclub and event venue with large capacity, DJ booth, dance floor, and full bar. Hosts private parties.",
        "website":      "https://westwaynyc.com",
        "contact":      "events@westwaynyc.com",
        "notes":        "Good capacity for 200-300, nightlife programming, DJ setup. Private events. Check for outdoor component.",
        "source_url":   "https://westwaynyc.com",
    },
    {
        "venue_name":   "Terrace at Tribeca Rooftop",
        "location":     "2 Desbrosses St, New York, NY 10013",
        "neighborhood": "Tribeca",
        "borough":      "Manhattan",
        "capacity":     "300",
        "venue_type":   "Rooftop Event Space",
        "description":  "Upscale Tribeca rooftop event space with Manhattan Bridge and Hudson River views. Purpose-built for private events.",
        "website":      "https://www.tribecaprivate.com",
        "contact":      "events@tribecaprivate.com",
        "notes":        "Bridge + waterfront views, full A/V, bar setup, private events only. Min spend likely $8K+.",
        "source_url":   "https://www.tribecaprivate.com",
    },
    {
        "venue_name":   "Top of The Standard",
        "location":     "848 Washington St, New York, NY 10014",
        "neighborhood": "Meatpacking District",
        "borough":      "Manhattan",
        "capacity":     "200",
        "venue_type":   "Hotel Rooftop",
        "description":  "Intimate rooftop event space at The Standard Hotel, High Line, with Hudson River and Manhattan views.",
        "website":      "https://www.standardhotels.com/new-york/properties/high-line",
        "contact":      "events@standardhotels.com",
        "notes":        "Hudson River views, Meatpacking District location, luxury finishes, private events.",
        "source_url":   "https://www.standardhotels.com",
    },
    {
        "venue_name":   "PUBLIC Hotel Rooftop — The Crown",
        "location":     "215 Chrystie St, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough":      "Manhattan",
        "capacity":     "250",
        "venue_type":   "Hotel Rooftop Bar",
        "description":  "Ian Schrager's PUBLIC Hotel rooftop bar with stunning LES views and vibrant nightlife scene.",
        "website":      "https://publichotels.com/new-york/eat-drink/the-crown",
        "contact":      "events@publichotels.com",
        "notes":        "LES views, strong nightlife scene, private event potential. Ian Schrager property.",
        "source_url":   "https://publichotels.com",
    },
    {
        "venue_name":   "Ophelia NYC",
        "location":     "3 Mitchell Pl, New York, NY 10017",
        "neighborhood": "Midtown East",
        "borough":      "Manhattan",
        "capacity":     "200",
        "venue_type":   "Rooftop Bar",
        "description":  "Art deco-inspired rooftop cocktail bar on the 26th floor with East River and skyline views. Private event hire available.",
        "website":      "https://ophelianyc.com",
        "contact":      "events@ophelianyc.com",
        "notes":        "East River views, art deco aesthetic, craft cocktails, private event capability.",
        "source_url":   "https://ophelianyc.com",
    },
    {
        "venue_name":   "Haven's Kitchen",
        "location":     "109 W 17th St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough":      "Manhattan",
        "capacity":     "200",
        "venue_type":   "Event Space / Garden",
        "description":  "Chelsea event space and culinary studio with rooftop terrace and garden, frequently hosting private events.",
        "website":      "https://havenskitchen.com/events/",
        "contact":      "events@havenskitchen.com",
        "notes":        "Rooftop terrace, full catering, private events. Intimate scale, ~200 max.",
        "source_url":   "https://havenskitchen.com",
    },
    {
        "venue_name":   "Catch Roof NYC",
        "location":     "21 9th Ave, New York, NY 10014",
        "neighborhood": "Meatpacking District",
        "borough":      "Manhattan",
        "capacity":     "250",
        "venue_type":   "Restaurant Rooftop",
        "description":  "Rooftop bar and lounge at Catch NYC with Manhattan skyline views, outdoor terrace, and private event capabilities.",
        "website":      "https://catchrestaurants.com/location/catch-roof/",
        "contact":      "events@catchrestaurants.com",
        "notes":        "Skyline views, Meatpacking District, private events, full bar and food service.",
        "source_url":   "https://catchrestaurants.com",
    },
    {
        "venue_name":   "Refinery Rooftop",
        "location":     "63 W 38th St, New York, NY 10018",
        "neighborhood": "Midtown",
        "borough":      "Manhattan",
        "capacity":     "250",
        "venue_type":   "Hotel Rooftop Event Space",
        "description":  "Industrial-chic rooftop at Refinery Hotel with Empire State Building views and dedicated private event space.",
        "website":      "https://www.refineryrooftop.com",
        "contact":      "events@refineryrooftop.com",
        "notes":        "Empire State Building views, private event buyout, full A/V, bar service. Mid-range pricing.",
        "source_url":   "https://www.refineryrooftop.com",
    },
    {
        "venue_name":   "The Skylot NYC",
        "location":     "232 W 15th St, New York, NY 10011",
        "neighborhood": "Chelsea",
        "borough":      "Manhattan",
        "capacity":     "200",
        "venue_type":   "Rooftop Event Space",
        "description":  "Intimate Chelsea rooftop event space with city views, DJ capability, and full bar for private events.",
        "website":      "https://theskylot.com",
        "contact":      "info@theskylot.com",
        "notes":        "Chelsea rooftop, DJ-friendly, private event hire. Verify current capacity and availability.",
        "source_url":   "https://theskylot.com",
    },
    {
        "venue_name":   "SIXTY Hotels LES Rooftop",
        "location":     "190 Allen St, New York, NY 10002",
        "neighborhood": "Lower East Side",
        "borough":      "Manhattan",
        "capacity":     "200",
        "venue_type":   "Hotel Rooftop",
        "description":  "Boutique hotel rooftop on LES with city views and private event capabilities. Known LES nightlife neighborhood.",
        "website":      "https://sixtyhotels.com/sixty-les",
        "contact":      "events.les@sixtyhotels.com",
        "notes":        "LES location, private events, boutique hotel rooftop. Verify current capacity.",
        "source_url":   "https://sixtyhotels.com",
    },
    {
        "venue_name":   "Brooklyn Bazaar",
        "location":     "150 Greenpoint Ave, Brooklyn, NY 11222",
        "neighborhood": "Greenpoint",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Event Venue / Outdoor Space",
        "description":  "Large Greenpoint event and music venue with rooftop deck, multiple rooms, and strong nightlife programming.",
        "website":      "https://brooklynbazaar.net",
        "contact":      "booking@brooklynbazaar.net",
        "notes":        "Rooftop deck, large capacity, nightlife events, bar service. Has hosted diverse cultural events.",
        "source_url":   "https://brooklynbazaar.net",
    },
    {
        "venue_name":   "LoanedOut at Brooklyn Navy Yard",
        "location":     "63 Flushing Ave, Brooklyn, NY 11205",
        "neighborhood": "Brooklyn Navy Yard",
        "borough":      "Brooklyn",
        "capacity":     "300",
        "venue_type":   "Rooftop Event Space",
        "description":  "Rooftop event space within the Brooklyn Navy Yard complex with city views and multi-purpose layout.",
        "website":      "https://brooklynnavyyard.org/visit/events",
        "contact":      "events@brooklynnavyyard.org",
        "notes":        "Navy Yard rooftop setting, outdoor terrace, industrial-chic. Good for large cultural events.",
        "source_url":   "https://brooklynnavyyard.org",
    },
    {
        "venue_name":   "Glasslands Gallery",
        "location":     "289 Kent Ave, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "250",
        "venue_type":   "Event Space / Rooftop",
        "description":  "Historic Williamsburg event space with rooftop access, waterfront proximity, and flexible layout for cultural events.",
        "website":      "https://glasslandsbrooklyn.com",
        "contact":      "info@glasslandsbrooklyn.com",
        "notes":        "Williamsburg waterfront, outdoor access, cultural events. Verify current operational status.",
        "source_url":   "https://glasslandsbrooklyn.com",
    },
    {
        "venue_name":   "The Williamsburg Hotel Rooftop",
        "location":     "96 Wythe Ave, Brooklyn, NY 11249",
        "neighborhood": "Williamsburg",
        "borough":      "Brooklyn",
        "capacity":     "200",
        "venue_type":   "Hotel Rooftop Bar",
        "description":  "Stylish rooftop pool bar at The Williamsburg Hotel with panoramic Manhattan views and private event capabilities.",
        "website":      "https://www.thewilliamsburghotel.com/rooftop",
        "contact":      "events@thewilliamsburghotel.com",
        "notes":        "Pool + rooftop views, Williamsburg, private events, full bar. Good SNITC aesthetic fit.",
        "source_url":   "https://www.thewilliamsburghotel.com",
    },
]
