"""
seeds.py — Curated seed brands known to match SNITC sponsor criteria.

These are pre-researched Black/Caribbean/Latin-owned brands with NYC presence.
The pipeline will still scrape their websites to pull live contact info.
"""

SEED_BRANDS = [
    # ── ALCOHOL / SPIRITS ──────────────────────────────────────────────────────
    {
        "brand_name": "Hella Cocktail Co.",
        "website": "https://hellacocktail.co",
        "category": "Alcohol/Beverages",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – Brooklyn",
        "founder": "Jomaree Pinkard, Eddie Simeon, Tobin Ludwig",
        "notes": "Brooklyn-based Black-owned cocktail bitters & mixers. Perfect for signature cocktail partnership at SNITC.",
    },
    {
        "brand_name": "Ten To One Rum",
        "website": "https://tentoonerum.com",
        "category": "Alcohol/Spirits",
        "diversity": "Caribbean-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Marc Farrell",
        "notes": "Caribbean-founded premium rum, Trinidad-born founder based in NYC. Ideal Afrobeats/Caribbean event partner.",
    },
    {
        "brand_name": "Uncle Nearest Premium Whiskey",
        "website": "https://unclenearest.com",
        "category": "Alcohol/Spirits",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Fawn Weaver",
        "notes": "Fastest-growing American whiskey brand, named after first known Black master distiller. Strong brand story.",
    },
    {
        "brand_name": "McBride Sisters Wine",
        "website": "https://mcbridesisters.com",
        "category": "Alcohol/Spirits",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Robin McBride, Andréa McBride John",
        "notes": "Largest Black-owned wine company in the US. Women-owned, strong community focus, great SNITC alignment.",
    },
    {
        "brand_name": "Brough Brothers Bourbon",
        "website": "https://broughbrothers.com",
        "category": "Alcohol/Spirits",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Victor, Christophe, and Bryson Yarbrough",
        "notes": "First Black-owned bourbon distillery in Kentucky, strong NYC market presence.",
    },
    {
        "brand_name": "Harlem Brewing Company",
        "website": "https://harlembrewing.com",
        "category": "Alcohol/Spirits",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – Harlem",
        "founder": "Celeste Beatty",
        "notes": "Harlem-based Black woman-owned brewery. Can't get more NYC-local than this.",
    },
    {
        "brand_name": "Equiano Rum",
        "website": "https://equianorum.com",
        "category": "Alcohol/Spirits",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Ian Burrell, Eku££Ekwueme",
        "notes": "Award-winning rum named after Olaudah Equiano, celebrating African heritage. Strong cultural alignment.",
    },
    {
        "brand_name": "Maison Noir Wines",
        "website": "https://maisonnoir.com",
        "category": "Alcohol/Spirits",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "André Hueston Mack",
        "notes": "Black-owned natural wine label by Harlem-raised sommelier. Mission-aligned with cultural tastemakers.",
    },

    # ── BEAUTY / WELLNESS ───────────────────────────────────────────────────────
    {
        "brand_name": "Golde",
        "website": "https://golde.co",
        "category": "Beauty/Wellness",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – Brooklyn",
        "founder": "Trinity Mouzon Wofford, Issey Kobori",
        "notes": "Brooklyn-based wellness brand by a 23-year-old Black founder. Young, vibrant, Instagram-native brand.",
    },
    {
        "brand_name": "Briogeo Hair Care",
        "website": "https://briogeohair.com",
        "category": "Beauty/Wellness",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Nancy Twine",
        "notes": "Black-owned clean haircare brand based in NYC. Strong multicultural audience.",
    },
    {
        "brand_name": "Nyakio Beauty",
        "website": "https://nyakio.com",
        "category": "Beauty/Wellness",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Nyakio Grieco",
        "notes": "African heritage-inspired skincare brand by Kenyan-American founder. Great diaspora cultural alignment.",
    },
    {
        "brand_name": "The Lip Bar",
        "website": "https://thelipbar.com",
        "category": "Beauty/Wellness",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Melissa Butler",
        "notes": "Black woman-owned cosmetics brand, NYC-founded. Very active on social media.",
    },
    {
        "brand_name": "Epara Skincare",
        "website": "https://eparaskincare.com",
        "category": "Beauty/Wellness",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Ozohu Adoh",
        "notes": "Luxury skincare brand rooted in African botanicals. Nigerian founder, growing NYC presence.",
    },
    {
        "brand_name": "Oui the People",
        "website": "https://ouipeople.com",
        "category": "Beauty/Wellness",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Karen Young",
        "notes": "Black woman-owned body care brand, strong community values and social presence.",
    },

    # ── FASHION / STREETWEAR ────────────────────────────────────────────────────
    {
        "brand_name": "Dur Doux",
        "website": "https://shopdurdoux.com",
        "category": "Fashion/Streetwear",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Cynthia and Tanya Samuel",
        "notes": "NYC-based sister-owned luxury fashion house with Haitian roots. Strong Caribbean diaspora alignment.",
    },
    {
        "brand_name": "Harlem's Heaven Hats",
        "website": "https://harlemsheaven.com",
        "category": "Fashion/Streetwear",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – Harlem",
        "founder": "Mae Reeves",
        "notes": "Iconic Harlem-based Black-owned millinery. Perfect Harlem cultural activation partner.",
    },
    {
        "brand_name": "Daily Paper",
        "website": "https://dailypaperclothing.com",
        "category": "Fashion/Streetwear",
        "diversity": "African-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Hussein Suleiman, Jefferson Osei, Abderrahmane Trabsini",
        "notes": "Africa-founded streetwear brand with NYC flagship. Strong Afrobeat and diaspora community ties.",
    },
    {
        "brand_name": "Fe Noel",
        "website": "https://fenoel.com",
        "category": "Fashion/Streetwear",
        "diversity": "Black-owned, Caribbean-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Felisha Noel",
        "notes": "Grenadian-American NYC designer, strong Caribbean diaspora identity. Perfect cultural fit for SNITC.",
    },

    # ── LIFESTYLE / CULTURE ─────────────────────────────────────────────────────
    {
        "brand_name": "Cécred",
        "website": "https://cecred.com",
        "category": "Beauty/Wellness",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Beyoncé Knowles-Carter",
        "notes": "Premium haircare brand — if budget allows, collaboration could elevate SNITC significantly.",
    },
    {
        "brand_name": "Partake Foods",
        "website": "https://partakefoods.com",
        "category": "Food/Beverage",
        "diversity": "Black-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Denise Woodard",
        "notes": "Black woman-owned allergy-friendly snack brand, NYC-based. Could provide event snacks/gifting.",
    },
    {
        "brand_name": "Siete Family Foods",
        "website": "https://sietefoods.com",
        "category": "Food/Beverage",
        "diversity": "Latino/Latina-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Veronica Garza",
        "notes": "Latino family-owned Mexican-heritage food brand. Strong cultural identity, huge social following.",
    },
    {
        "brand_name": "Avec Drinks",
        "website": "https://avecdrinks.com",
        "category": "Food/Beverage",
        "diversity": "BIPOC-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Brice Mastroluca, Nick Vodovoz",
        "notes": "Trendy sparkling cocktail mixer brand popular with young urban audiences. Good event activation fit.",
    },
    {
        "brand_name": "Brooklyn Brewery",
        "website": "https://brooklynbrewery.com",
        "category": "Alcohol/Spirits",
        "diversity": "BIPOC-owned",
        "nyc_connection": "Yes – Brooklyn",
        "founder": "Steve Hindy, Tom Potter",
        "notes": "Iconic Brooklyn craft brewery — well known, community-oriented, natural SNITC sponsor target.",
    },
    {
        "brand_name": "Ashé Cultural Arts Center",
        "website": "https://ashecac.org",
        "category": "Lifestyle",
        "diversity": "Black-owned",
        "nyc_connection": "Yes – Brooklyn",
        "founder": "Carol Bebelle, Douglas Redd",
        "notes": "Brooklyn-based Afrocentric cultural space. Could be a cross-promotional partner.",
    },
    {
        "brand_name": "Nemi Sparkling",
        "website": "https://nemisparkling.com",
        "category": "Food/Beverage",
        "diversity": "Latino/Latina-owned, Women-owned",
        "nyc_connection": "Yes – NYC",
        "founder": "Sharon Cittone",
        "notes": "Hibiscus-based sparkling drinks brand with Caribbean/Latin cultural roots. Great non-alcoholic option.",
    },
]
